language: minimal
os: linux
dist: xenial
services:
  - docker
jobs:
  include:
    - stage: build docker image
      script:
        - git checkout ${TRAVIS_BRANCH}
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t $DOCKER_USERNAME/cppkg-test:travis-${TRAVIS_COMMIT} .
        - docker images
        - docker push $DOCKER_USERNAME/cppkg-test:travis-${TRAVIS_COMMIT}
    - stage: test
      script:
        - docker run -e CODECOV_TOKEN=${CODECOV_TOKEN}
          --rm $DOCKER_USERNAME/cppkg-test:travis-${TRAVIS_COMMIT}
notifications:
  email: false
branches:
  except:
  - legacy
  # safelist
  only:
  - master
  - /experimental(-.*)?/
  - stable
